version: '3.8'

services:
  mongo-service:
    image: mongo:latest
    container_name: container_mongo
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      network_server:
        ipv4_address: 10.16.1.2
    volumes:
      - volume_mongo:/data/db

  node-red-service:
    image: nodered/node-red:latest
    container_name: container_node-red
    restart: always
    environment:
      TZ: "Asia/Bangkok"
    ports:
      - "1880:1880"
    networks:
      network_server:
        ipv4_address: 10.16.1.3
    volumes:
      - volume_node-red:/data

  emqx-service:
    image: emqx/emqx:latest
    container_name: container_emqx
    restart: always
    env_file:
      - ./.env
    environment:
      EMQX_LISTENER__TCP__EXTERNAL: ${EMQX_LISTENER__TCP__EXTERNAL}
      EMQX_LISTENER__WS__EXTERNAL: ${EMQX_LISTENER__WS__EXTERNAL}
      EMQX_LISTENER__HTTPS__EXTERNAL: ${EMQX_LISTENER__HTTPS__EXTERNAL}
      EMQX_LISTENER__MQTT__EXTERNAL: ${EMQX_LISTENER__MQTT__EXTERNAL}
      EMQX_LISTENER__WS__MQTT__EXTERNAL: ${EMQX_LISTENER__WS__MQTT__EXTERNAL}
      EMQX_LISTENER__WSS__MQTT__EXTERNAL: ${EMQX_LISTENER__WSS__MQTT__EXTERNAL}
      EMQX_LISTENER__TCP__INTERNAL: ${EMQX_LISTENER__TCP__INTERNAL}
      EMQX_LISTENER__WS__INTERNAL: ${EMQX_LISTENER__WS__INTERNAL}
      EMQX_DASHBOARD__LISTENER__HTTP: ${EMQX_DASHBOARD__LISTENER__HTTP}
      EMQX_DASHBOARD__DEFAULT_USERNAME: ${EMQX_DASHBOARD__DEFAULT_USERNAME}
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${EMQX_DASHBOARD__DEFAULT_PASSWORD}
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "11883:11883"
      - "18083:18083"
      - "4370:4370"
      - "5369:5369"
    networks:
      network_server:
        ipv4_address: 10.16.1.4

  api:
    build:
      context: api
    container_name: container_fast-api
    restart: "no"
    env_file:
      - ./.env
    environment:
      PORT: 8899
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    depends_on:
      - mongo-service
    volumes:
      - ./api/src:/api:rw
      - ./api/images:/images:rw
    ports:
      - "8899:80"
    networks:
      network_server:
        ipv4_address: 10.16.1.5

  dashboard:
    build:
      context: dashboard
    container_name: container_dashboard
    restart: "no"
    env_file:
      - ./.env
    environment:
      PORT: 8501
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    depends_on:
      - mongo-service
    ports:
      - "8501:8501"
    networks:
      network_server:
        ipv4_address: 10.16.1.6

volumes:
  volume_mongo:
  volume_node-red:

networks:
  network_server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.16.1.0/24
          gateway: 10.16.1.1